import type { OriginationApplication } from '@/types';
import { generateId } from './format';

export const mockApplications: OriginationApplication[] = [
  {
    id: generateId('app'),
    businessName: 'Zanzibar Spice Traders',
    applicantName: 'Omar Said',
    requestedAmount: 150000,
    tradeCategory: 'Agriculture',
    cluster: 'Mombasa',
    stage: 'ai_review',
    submittedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    aiScore: 78,
    phoneDataFound: true,
    smsConsent: true,
  },
  {
    id: generateId('app'),
    businessName: 'Kilimani Auto Spares',
    applicantName: 'David Kariuki',
    requestedAmount: 450000,
    tradeCategory: 'Retail',
    cluster: 'Nairobi',
    stage: 'human_review',
    submittedAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    aiScore: 42,
    phoneDataFound: true,
    smsConsent: true,
  },
  {
    id: generateId('app'),
    businessName: 'Lake Victoria Fisheries',
    applicantName: 'Grace Achieng',
    requestedAmount: 80000,
    tradeCategory: 'Agriculture',
    cluster: 'Kisumu',
    stage: 'pending_data',
    submittedAt: new Date(Date.now() - 3600000 * 4).toISOString(),
    phoneDataFound: false,
    smsConsent: false,
  },
  {
    id: generateId('app'),
    businessName: 'TechHub Repair Centre',
    applicantName: 'Brian Mutua',
    requestedAmount: 200000,
    tradeCategory: 'Services',
    cluster: 'Nairobi',
    stage: 'approved',
    submittedAt: new Date(Date.now() - 86400000 * 12).toISOString(),
    aiScore: 88,
    phoneDataFound: true,
    smsConsent: true,
  },
  {
    id: generateId('app'),
    businessName: 'Coastal Hardware',
    applicantName: 'Aisha Mohammed',
    requestedAmount: 600000,
    tradeCategory: 'Retail',
    cluster: 'Mombasa',
    stage: 'rejected',
    submittedAt: new Date(Date.now() - 86400000 * 15).toISOString(),
    aiScore: 24,
    phoneDataFound: true,
    smsConsent: true,
  },
];
